@api = http://localhost:3000/empleado

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "Puesto": "Desarrollador",
    "ValorDocumentoIdentidad": "123456789",
    "Nombre": "Juan",
    "FechaContratacion": "2021-01-01",
}
